export const ERR_NOT_ONLINE = 'ERR_NOT_ONLINE';
export const ERR_INVALID_SESSION = 'ERR_INVALID_SESSION';
export const INVALID_PROMPT = 'INVALID_PROMPT';
export const GPT_EXCEEDED_LIMIT = 'GPT_EXCEEDED_LIMIT';
